---
name: Test install

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  ubuntu-test-install:
    env:
      BUILD_TYPE: Release
      CXXFLAGS: -pedantic -Werror -Wextra
      INSTALL_PREFIX: /usr
      LUA_VERSION: 5.3
      OSMFILE: monaco-latest.osm.pbf
      OSMURL: https://download.geofabrik.de/europe/monaco-latest.osm.pbf
      POSTGIS_VERSION: 3
      POSTGRESQL_VERSION: 12

    name: Build, install & import OSM data (Ubuntu ${{ matrix.image_tag }})

    runs-on: ubuntu-${{ matrix.image_tag }}

    strategy:
      fail-fast: false
      matrix:
        image_tag:
          - 18.04  # Clang 6.0.0  | GCC 7.5.0
          - 20.04  # Clang 10.0.0 | GCC 9.4.0
          - 22.04  # Clang 14.0.0 | GCC 11.2.0

    steps:
      - uses: actions/checkout@v3
      - name: Show installed PostgreSQL packages
        run: dpkg --list | grep -i -e postgis -e postgresql | sort
      - name: Disregard stringop-overread warnings (Ubuntu 22.04/GCC 11)
        run: echo "CXXFLAGS=${CXXFLAGS} -Wno-stringop-overread" >> $GITHUB_ENV
        if: matrix.image_tag == 22.04
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/build
      - uses: ./.github/actions/install
      - name: Set up test databases
        run: |
          sudo systemctl start postgresql
          sudo -u postgres createuser runner
          sudo -u postgres createdb -O runner o2ptest
          sudo -u postgres psql o2ptest -c "CREATE EXTENSION hstore;"
          sudo -u postgres psql o2ptest -c "CREATE EXTENSION postgis;"
        working-directory: /tmp
      - name: Remove repository
        # Remove contents of workspace to be sure the install runs independently
        run: rm -frv "${GITHUB_WORKSPACE}"/*
      - name: Show man pages
        run: |
          man -P cat osm2pgsql
          man -P cat osm2pgsql-replication
      - name: Download test file
        run: wget --quiet $OSMURL
        working-directory: /tmp
      - name: Test run of osm2pgsql
        run: |
          ${INSTALL_PREFIX}/bin/osm2pgsql \
            -v -d o2ptest --slim $OSMFILE
        working-directory: /tmp
      - name: Test run osm2pgsql-replication
        run: |
          ${INSTALL_PREFIX}/bin/osm2pgsql-replication init \
            -v -d o2ptest
          ${INSTALL_PREFIX}/bin/osm2pgsql-replication status \
            -v -d o2ptest
          ${INSTALL_PREFIX}/bin/osm2pgsql-replication update \
            -v -d o2ptest --once --max-diff-size=1
          ${INSTALL_PREFIX}/bin/osm2pgsql-replication status \
            -v -d o2ptest --json
        working-directory: /tmp
